/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tietie_postcard_func_LameEncoder */

#ifndef _Included_com_tietie_postcard_func_LameEncoder
#define _Included_com_tietie_postcard_func_LameEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tietie_postcard_func_LameEncoder
 * Method:    onCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tietie_postcard_func_LameEncoder_onCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_tietie_postcard_func_LameEncoder
 * Method:    onEncode
 * Signature: ([B[B)V
 */
JNIEXPORT jint JNICALL Java_com_tietie_postcard_func_LameEncoder_onEncode
  (JNIEnv *, jobject, jshortArray, jbyteArray);
/*
 * Class:     com_tietie_postcard_func_LameEncoder
 * Method:    onFinish
 * Signature: ([B)V
 */
JNIEXPORT jint JNICALL Java_com_tietie_postcard_func_LameEncoder_onFinish
  (JNIEnv *, jobject, jbyteArray);
/*
 * Class:     com_tietie_postcard_func_LameEncoder
 * Method:    onDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tietie_postcard_func_LameEncoder_onDestory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
